"""add unique constraints per user and enforce currency code

Revision ID: 694ece133b03
Revises: 6f9f8747dc6f
Create Date: 2026-08-03 22:59:40.680255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694ece133b03'
down_revision: Union[str, Sequence[str], None] = '6f9f8747dc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('credit_type_code_key'), 'credit_type', type_='unique')
    op.create_unique_constraint('uq_credit_type_user_code', 'credit_type', ['user_id', 'code'])
    op.alter_column('currency', 'code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10),
               nullable=False)
    op.create_unique_constraint('uq_currency_code', 'currency', ['code'])
    op.drop_constraint(op.f('debit_type_code_key'), 'debit_type', type_='unique')
    op.create_unique_constraint('uq_debit_type_user_code', 'debit_type', ['user_id', 'code'])
    op.alter_column('wallet_type', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_constraint(op.f('wallet_type_code_key'), 'wallet_type', type_='unique')
    op.create_unique_constraint('uq_wallet_type_user_code', 'wallet_type', ['user_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wallet_type_user_code', 'wallet_type', type_='unique')
    op.create_unique_constraint(op.f('wallet_type_code_key'), 'wallet_type', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('wallet_type', 'code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('uq_debit_type_user_code', 'debit_type', type_='unique')
    op.create_unique_constraint(op.f('debit_type_code_key'), 'debit_type', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_currency_code', 'currency', type_='unique')
    op.alter_column('currency', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('uq_credit_type_user_code', 'credit_type', type_='unique')
    op.create_unique_constraint(op.f('credit_type_code_key'), 'credit_type', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
