"""fix credit operations

Revision ID: a4171db90c88
Revises: 139d1f239e84
Create Date: 2026-07-27 18:04:59.408661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4171db90c88'
down_revision: Union[str, Sequence[str], None] = '139d1f239e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_operation', 'credit_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('debit_operation', 'debit_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debit_operation', 'debit_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credit_operation', 'credit_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
