"""add hashed_passwordand google_id to user

Revision ID: fbfffbd7b540
Revises: 536ee0ccaa09
Create Date: 2026-07-01 12:43:53.479003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfffbd7b540'
down_revision: Union[str, Sequence[str], None] = '536ee0ccaa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('app_user', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint("uq_app_user_google_id", 'app_user', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_app_user_google_id", 'app_user', type_='unique')
    op.drop_column('app_user', 'google_id')
    op.drop_column('app_user', 'hashed_password')
    # ### end Alembic commands ###
